name = "Distributor Pricing"
client_id = "b9a1460caf799a3c393ddaa11f80f50e"
application_url = "https://shoreline-ochre.vercel.app"
embedded = false

[access_scopes]
# read_customers is required to access customer tags in Functions
scopes = "read_customers,read_products,write_discounts"

[auth]
redirect_urls = ["https://shoreline-ochre.vercel.app/auth/callback"]

[webhooks]
api_version = "2025-10"

[pos]
embedded = false
